# Generated by Django 4.1.7 on 2023-06-17 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_like_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like_Posts',
            new_name='Like_Post',
        ),
    ]
