# Generated by Django 4.1.7 on 2023-06-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_like_posts_like_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like_Post',
            new_name='LikePost',
        ),
        migrations.RenameField(
            model_name='likepost',
            old_name='id_post',
            new_name='post_id',
        ),
    ]
