# Generated by Django 4.1.7 on 2023-06-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_like_post_likepost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikePost',
            new_name='Like_Post',
        ),
        migrations.RenameField(
            model_name='like_post',
            old_name='post_id',
            new_name='id_post',
        ),
    ]
